#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         2

bspc config split_ratio          0.5
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true

bspc config single_monocle            true
bspc config honor_size_hints true

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true
bspc config pointer_motion_interval   7
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

## Gaps 
bspc config window_gap 10;
bspc config top_padding 50
bspc config left_padding 5
bspc config right_padding 5
bspc config bottom_padding 5
 
## Border Color
bspc config focused_border_color "#CBA6F7"
bspc config normal_border_color "#9399B2"
bspc config urgent_border_color "#F38BA8"
bspc config border_width 2

# AutoStart apps
sxhkd &
picom --config $HOME/.config/bspwm/picom/picom.conf -b &
feh --bg-scale $(cat $HOME/.config/bspwm/wallpaper)  &
dunst &
$HOME/.config/bspwm/polybar/launch.sh &
setxkbmap -model pc104 -layout us,ara -variant ,, -option grp:alt_shift_toggle &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1 &
xsetroot -cursor_name left_ptr &
xss-lock --transfer-sleep-lock -- i3lock -i ~/Pictures/i3lock/image.png &
